version: "3.9" # Especifique a versão do Docker Compose
services:
  mysqldb:
    image: mysql:8.0.40
    container_name: brecho_db
    restart: unless-stopped
    volumes:
      - ./backend/src/config:/docker-entrypoint-initdb.d
 
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT # Not necessary, MySQL uses 3306 by default. Remove this.
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT # Make sure this matches the internal port used (3306 by default) if different. Remove otherwise.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/bazarUp
    container_name: Bazar-Api
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=$MYSQL_DOCKER_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true


