version: "3.8"
services:
  db:
    image: mysql:8.0.40
    container_name: brecho_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8232
      MYSQL_DATABASE: brecho
      MYSQL_USER: andersonUser
      MYSQL_PASSWORD: Anderson8232
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: brecho_backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: andersonUser
      DB_PASSWORD: Anderson8232
      DB_NAME: brecho

  frontend:
    build:
      context: ./frontend
    container_name: brecho_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
